kind: Namespace
apiVersion: v1
metadata:
  name: demand
  labels:
    name: demand


---


kind: Deployment
apiVersion: apps/v1
metadata:
  name: demand-flow-apis
  labels:
    app: demand-flow-apis
  namespace: demand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demand-flow-apis
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: demand-flow-apis
        tier: backend
        track: stable
    spec:
      containers:
      - name: demand-flow-apis
        image: gayatriganesanibm/demand-flow-apis:dec15v4
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: demand-flow-apis
  namespace: demand
spec:
  selector:
    app: demand-flow-apis
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
